defaults:
  ids:
    leftDriveTalonLeader: 1
    leftDriveTalonFollower: 2
    rightDriveTalonLeader: 3
    rightDriveTalonFollower: 4
    shooterLeader: 5
    shooterFollower: 6
    armLeader: 7
    armFollower: 8
    feeder: 9
  bag:
    kt: 0.00819095836320447
    kv: 0.008398404204492988
    resistance: 0.22805452519362293
    inertia: "{{ .5 * .32 * (.0404/2) * (.0404/2 )}}" # .32kg cylinder @ 40.4 diameter... Inertia is I=.5 * m * r^2
  neo:
    stallTorque: 2.6
    stallCurrent: 105
    voltage: 12
    maxRPM: 5676
    mass: .425
    diameter: .06
  falcon:
    stallTorque: 4.69
    stallCurrent: 257
    voltage: 12
    maxRPM: 6380
    mass: .5
    diameter: .06
  shooterGearing: "{{ .48 / 1 }}"
  juniorGearing: "{{ 242.0/27.0 }}"
  driveGearing: "{{ 1 }}"
  driveInertia: "{{ .5 * 0.453592 * (.5 * 0.1524 * .5 * 0.1524) }}"
hideFollowers: true
driveBase:
  mass: 39.3051396
  radius: 0.3145536
  wheelRadius: 0.07762
  robotInertia: 2.1621037
  wheelInertia: 1.0E-4
  viscousFriction: 0.04666464678901319
  gearRatio: "{{ 10 +  22 / 25 }}"
startPosition:
  x: 1.54
  y: 5.33
  heading: 0 #"{{ -3.14159 / 2 }}"
transmissions:
- motors:
  - id: "{{ defaults.ids.leftDriveTalonLeader }}"
    name: "Left Drive ({{ defaults.ids.leftDriveTalonLeader }})"
    model: falcon
    stallTorque: "{{ defaults.falcon.stallTorque }}"
    stallCurrent: "{{ defaults.falcon.stallCurrent }}"
    voltage: "{{ defaults.falcon.voltage }}"
    maxRPM: "{{ defaults.falcon.maxRPM }}"
    mass: "{{ defaults.falcon.mass }}"
    diameter: "{{ defaults.falcon.diameter }}"
    encoderCountsPerRevolution: 2048
    leftDrive: true
  - id: "{{ defaults.ids.leftDriveTalonFollower }}"
    name: "Left Drive Follower ({{ defaults.ids.leftDriveTalonFollower }})"
    model: falcon
    stallTorque: "{{ defaults.falcon.stallTorque }}"
    stallCurrent: "{{ defaults.falcon.stallCurrent }}"
    voltage: "{{ defaults.falcon.voltage }}"
    maxRPM: "{{ defaults.falcon.maxRPM }}"
    mass: "{{ defaults.falcon.mass }}"
    diameter: "{{ defaults.falcon.diameter }}"
    encoderCountsPerRevolution: 2048
    leftDrive: true
  gearRatio: "{{ defaults.driveGearing }}"
  efficiency: 1
- motors:
  - id: "{{ defaults.ids.rightDriveTalonLeader }}"
    name: "Right Drive ({{ defaults.ids.rightDriveTalonLeader }})"
    model: falcon
    stallTorque: "{{ defaults.falcon.stallTorque }}"
    stallCurrent: "{{ defaults.falcon.stallCurrent }}"
    voltage: "{{ defaults.falcon.voltage }}"
    maxRPM: "{{ defaults.falcon.maxRPM }}"
    mass: "{{ defaults.falcon.mass }}"
    diameter: "{{ defaults.falcon.diameter }}"
    encoderCountsPerRevolution: 2048
    rightDrive: true
  - id: "{{ defaults.ids.rightDriveTalonFollower }}"
    name: "Right Drive Follower ({{ defaults.ids.rightDriveTalonFollower }})"
    model: falcon
    stallTorque: "{{ defaults.falcon.stallTorque }}"
    stallCurrent: "{{ defaults.falcon.stallCurrent }}"
    voltage: "{{ defaults.falcon.voltage }}"
    maxRPM: "{{ defaults.falcon.maxRPM }}"
    mass: "{{ defaults.falcon.mass }}"
    diameter: "{{ defaults.falcon.diameter }}"
    encoderCountsPerRevolution: 2048
    rightDrive: true
  gearRatio: "{{ defaults.driveGearing }}"
  efficiency: 1
- motors:
  - id: "{{ defaults.ids.armLeader }}"
    name: "Arm ({{ defaults.ids.armLeader }})"
    model: bag
    kt: "{{ defaults.bag.kt }}"
    kv: "{{ defaults.bag.kv }}"
    resistance: "{{ defaults.bag.resistance }}"
    inertia: "{{ defaults.bag.inertia }}"
    encoderCountsPerRevolution: 2048
  - id: "{{ defaults.ids.armFollower }}"
    name: "Arm ({{ defaults.ids.armFollower }})"
    model: bag
    kt: "{{ defaults.bag.kt }}"
    kv: "{{ defaults.bag.kv }}"
    resistance: "{{ defaults.bag.resistance }}"
    inertia: "{{ defaults.bag.inertia }}"
    encoderCountsPerRevolution: 2048
  gearRatio: "{{ defaults.juniorGearing }}"
  efficiency: .8
- motors:
    - id: 7
      name: Spark Left Motor (7)
      model: neo
      stallTorque: "{{ defaults.neo.stallTorque }}"
      stallCurrent: "{{ defaults.neo.stallCurrent }}"
      voltage: "{{ defaults.neo.voltage }}"
      maxRPM: "{{ defaults.neo.maxRPM }}"
      mass: "{{ defaults.neo.mass }}"
      diameter: "{{ defaults.neo.diameter }}"
    - id: 8
      name: Spark Left Follower (8)
      model: neo
      stallTorque: "{{ defaults.neo.stallTorque }}"
      stallCurrent: "{{ defaults.neo.stallCurrent }}"
      voltage: "{{ defaults.neo.voltage }}"
      maxRPM: "{{ defaults.neo.maxRPM }}"
      mass: "{{ defaults.neo.mass }}"
      diameter: "{{ defaults.neo.diameter }}"
  gearRatio: "{{ defaults.juniorGearing }}"
  efficiency: 1
- motors:
    - id: 9
      name: Spark Right Motor (9)
      model: neo
      stallTorque: "{{ defaults.neo.stallTorque }}"
      stallCurrent: "{{ defaults.neo.stallCurrent }}"
      voltage: "{{ defaults.neo.voltage }}"
      maxRPM: "{{ defaults.neo.maxRPM }}"
      mass: "{{ defaults.neo.mass }}"
      diameter: "{{ defaults.neo.diameter }}"
    - id: 10
      name: Spark Right Follower (10)
      model: neo
      stallTorque: "{{ defaults.neo.stallTorque }}"
      stallCurrent: "{{ defaults.neo.stallCurrent }}"
      voltage: "{{ defaults.neo.voltage }}"
      maxRPM: "{{ defaults.neo.maxRPM }}"
      mass: "{{ defaults.neo.mass }}"
      diameter: "{{ defaults.neo.diameter }}"
  gearRatio: "{{ defaults.juniorGearing }}"
  efficiency: 1
- motors:
    - id: "{{ defaults.ids.shooterLeader }}"
      name: "Shooter ({{ defaults.ids.shooterLeader }})"
      model: Falcon
      stallTorque: "{{ defaults.falcon.stallTorque }}"
      stallCurrent: "{{ defaults.falcon.stallCurrent }}"
      voltage: "{{ defaults.falcon.voltage }}"
      maxRPM: "{{ defaults.falcon.maxRPM }}"
      mass: "{{ defaults.falcon.mass * 10 }}"
      diameter: "{{ defaults.falcon.diameter }}"
    - id: "{{ defaults.ids.shooterFollower }}"
      name: "Shooter Follower ({{ defaults.ids.shooterFollower }})"
      model: Falcon
      stallTorque: "{{ defaults.falcon.stallTorque }}"
      stallCurrent: "{{ defaults.falcon.stallCurrent }}"
      voltage: "{{ defaults.falcon.voltage }}"
      maxRPM: "{{ defaults.falcon.maxRPM }}"
      mass: "{{ defaults.falcon.mass * 10 }}"
      diameter: "{{ defaults.falcon.diameter }}"
  gearRatio: "{{ defaults.shooterGearing }}"
  efficiency: 1.0
- motors:
    - id: "{{ defaults.ids.feeder }}"
      name: "Feeder ({{ defaults.ids.feeder }})"
      model: bag
      kt: "{{ defaults.bag.kt }}"
      kv: "{{ defaults.bag.kv }}"
      resistance: "{{ defaults.bag.resistance }}"
      inertia: "{{ defaults.bag.inertia }}"
      encoderCountsPerRevolution: 8192

solenoids:
  - module: 0
    name: Arm Double Solenoid (0)
  - module: 1
    name: Arm Single Solenoid (1)
